# bài tập numpy

In [2]:
import numpy as np

#### 1.Given a 1D array, negate all elements which are between 3 and 8, in place (not created a new array).


In [16]:
arr=np.random.randint(0,10,10)
arr

array([1, 6, 6, 5, 5, 1, 7, 9, 8, 7])

In [18]:
arr=arr[(3>arr) | (arr>8)]
arr

array([1, 1, 9])

#### 2.Create random vector of size 10 and replace the maximum value by 0

In [19]:
x=np.array(np.random.randint(0,1000000,10))

In [20]:
x[np.where(x==x.max())]=0
x

array([     0,   7816, 150635, 121340,  16497, 418581, 526063, 520923,
       123444, 440688])

#### 3.How to find common values between two arrays?

In [38]:
x=np.random.randint(10,100,10)
y=np.random.randint(0,100,10)
x,y

(array([64, 89, 65, 76, 78, 35, 52, 43, 56, 80]),
 array([71,  3, 63, 73, 35, 94, 39, 13,  8, 47]))

In [39]:
np.intersect1d(x,y)

array([35])

#### 4.Reverse a vector (first element becomes last)

In [40]:
X=np.random.randint(10,100,10)
X

array([44, 74, 78, 25, 23, 29, 68, 95, 29, 17])

In [41]:
X=X[::-1]
X

array([17, 29, 95, 68, 29, 23, 25, 78, 74, 44])

#### 5.Create a 3x3 matrix with values ranging from 0 to 8

In [42]:
X=np.arange(0,9,1).reshape((3,3))
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6.Find indices of non-zero elements from the array [1,2,0,0,4,0]

In [43]:
X=np.array([1,2,0,0,4,0])
X=np.where(X!=0)

In [44]:
X

(array([0, 1, 4]),)

#### 7.Create a 3x3x3 array with random values

In [45]:
X=np.random.randint(0,10000,27).reshape((3,3,3))

In [46]:
X

array([[[6194,  664,   56],
        [8176, 8508, 9781],
        [8830, 1594, 7072]],

       [[4784, 1204, 5570],
        [4537, 5624, 6396],
        [8341, 2972, 3596]],

       [[8056, 8911, 5560],
        [3414, 4037, 2714],
        [9863, 3346, 7506]]])

#### 8.Create a random vector of size 30 and find the mean value

In [47]:
X=np.random.randn(30)

In [48]:
X

array([-0.26336556,  1.10784915, -0.36429646,  0.55590396,  0.28911583,
        0.12147826, -1.10703605,  0.80694482,  0.63275439, -0.57061778,
       -0.36265314, -0.54711538, -1.80252208,  0.60638769, -0.24512882,
        0.61444771, -0.84968991, -0.25416708, -0.18357967,  1.13592478,
        1.48612379,  0.1184055 ,  0.47067041,  0.23203463, -0.76514211,
       -1.19366551, -1.70467461, -0.66545939, -0.19066713,  1.66836996])

In [49]:
np.average(X)

-0.04077899380686931

#### 9.Create a 2d array with 1 on the border and 0 inside

In [80]:
a=np.ones((5,5))

In [81]:
a[1:4,1:4]=0

In [82]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 10.Given an array x of 20 integers in the range (0, 100)

In [138]:
x=np.random.randint(0,100,20)
x

array([57, 51, 83, 48, 98, 35, 88,  1, 67, 28, 70, 15, 87,  5, 18,  6, 87,
       54, 99, 17])

In [139]:
y = np.random.uniform(0, 20)
y

12.139116251683964

In [147]:
np.where(abs(x-y)==min(abs(x-y)))

(array([11]),)