# bài tập numpy

In [1]:
import numpy as np

#### 1.Given a 1D array, negate all elements which are between 3 and 8, in place (not created a new array).


In [10]:
arr=np.array(list(map(int,input().split(" "))))
arr

1 2 3 3 4 4 5 5 5 6 6 5 23 5 43313 3412 13


array([    1,     2,     3,     3,     4,     4,     5,     5,     5,
           6,     6,     5,    23,     5, 43313,  3412,    13])

In [8]:
arr=np.array([-i if i in range(3,8) else i for i in list(arr)])
arr

array([      1,       2,      -3,      -3,      -4,      -4,      -5,
            -5,      -5,      -6,      -6,      -5,      23,      -5,
           423,   23423,   42323, 4234234,   23423,     234])

#### 2.Create random vector of size 10 and replace the maximum value by 0

In [39]:
x=np.array(np.random.randint(0,1000000,10))

In [40]:
x[np.where(x==x.max())]=0
x

array([     0, 324286, 904165, 934801,  37163, 402822, 868114, 494654,
       980581, 812656])

#### 3.How to find common values between two arrays?

In [56]:
x=np.random.randint(10,100,10)
y=np.random.randint(0,100,10)
x,y

(array([65, 64, 82, 75, 24, 20, 86, 42, 71, 43]),
 array([85, 11, 97,  7, 62, 11, 64, 79, 46, 86]))

In [59]:
[i for i in x if i in y]

[64, 86]

#### 4.Reverse a vector (first element becomes last)

In [70]:
X=np.random.randint(10,100,10)
X

array([84, 75, 58, 40, 97, 63, 26, 30, 79, 89])

In [72]:
X=X[::-1]
X

array([84, 75, 58, 40, 97, 63, 26, 30, 79, 89])

#### 5.Create a 3x3 matrix with values ranging from 0 to 8

In [95]:
X=np.arange(0,9,1).reshape((3,3))
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6.Find indices of non-zero elements from the array [1,2,0,0,4,0]

In [114]:
X=np.array([1,2,0,0,4,0])
X=np.where(X!=0)

In [115]:
X

(array([0, 1, 4]),)

#### 7.Create a 3x3x3 array with random values

In [106]:
X=np.random.randint(0,10000,27).reshape((3,3,3))

In [107]:
X

array([[[9015,  137, 3817],
        [7811, 8089, 5680],
        [3364, 2107, 6382]],

       [[2088, 5490, 7151],
        [3813, 8532, 5315],
        [2659, 2223, 1587]],

       [[3396, 9560,   99],
        [5013, 6460, 2362],
        [2102, 1432, 5980]]])

#### 8.Create a random vector of size 30 and find the mean value

In [116]:
X=np.random.randn(30)

In [117]:
X

array([ 1.41455587, -0.1719059 ,  0.4678738 ,  2.39625384, -1.42117927,
       -0.9388889 , -0.49935841, -1.4318672 ,  0.09141477, -0.8628758 ,
       -0.82221558, -0.58092269,  0.44695307, -0.1216066 , -0.05606158,
        0.92476291, -1.26322999, -0.44066236,  1.01620375, -2.11940763,
        1.00675038,  0.73334109, -1.0304775 , -0.78615066, -0.93954602,
        0.33181441, -0.30531303,  0.40405058, -0.27173423, -0.12204539])

In [122]:
np.average(X)

-0.16504914234440024

#### 9.Create a 2d array with 1 on the border and 0 inside

In [128]:
a=np.zeros((5,5))

In [129]:
m,n= a.shape

In [130]:
for i in range(m):
    a[i][0]=1
    a[i][n-1]=1
for i in range(n):
    a[0][i]=1
    a[m-1][i]=1

In [131]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 10.Given an array x of 20 integers in the range (0, 100)

In [133]:
X=np.random.randint(0,100,20)
X

array([80, 94, 89,  0, 26, 27, 53, 71, 31, 66, 20, 43, 92, 91, 16, 93, 98,
       46, 13, 54])