In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data= pd.read_csv('data.csv')

In [4]:
X0=data.iloc[:,:1]
X1=data.iloc[:,1:2]
X2=data.iloc[:,2:3]
Y =data.iloc[:,3:4]

In [5]:
X=np.array(X0)
X=np.concatenate((X,np.array(X1)),axis=1)
X=np.concatenate((X,np.array(X2)),axis=1)
print(X)
Y=np.array(Y)
Y

[[ 73  80  75]
 [ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]


array([[152],
       [185],
       [180],
       [196],
       [142],
       [101],
       [149],
       [115],
       [175],
       [164],
       [141],
       [141],
       [184],
       [152],
       [148],
       [192],
       [147],
       [183],
       [177],
       [159],
       [177],
       [175],
       [175],
       [149],
       [192]])

In [6]:
m,n=np.shape(X)
c=0
theta=[0 for i in range(n)]
lr=0.0001

epoch=1000

for i in range(epoch):
    Y_predict=sum(X*theta,axis=1)
    #y_predict=np.zeros(np.shape(Y))
    #for j in range(len(X)):
    #    value=X[j][0]*theta[0]+X[j][1]*theta[1]+X[j][2]*theta[2]
    #    y_predict[j][0]=value
    G_theta=[(-1/m)*sum(X[:,i-1:i]*(Y-y_predict)) for i in range(1,n+1)]
    c1=(-1/m)*sum((Y-y_predict))
    for j in range(len(theta)):
        theta[j]=theta[j]-lr*G_theta[j]

TypeError: sum() takes no keyword arguments

In [26]:
Y_predict=[]
for i in X:
    Y_predict.append(i[0]*theta[0]+i[1]*theta[1]+i[2]*theta[2]+c)

In [27]:
Y_predict

[array([152.87096813]),
 array([184.85707056]),
 array([181.47509196]),
 array([198.75112623]),
 array([140.34334282]),
 array([105.31103899]),
 array([150.10760202]),
 array([113.11533438]),
 array([174.37762821]),
 array([164.0698523]),
 array([143.81354057]),
 array([142.72238981]),
 array([186.37008832]),
 array([153.411701]),
 array([151.08758393]),
 array([188.54205032]),
 array([145.1020913]),
 array([180.58824237]),
 array([177.32791345]),
 array([158.74594641]),
 array([175.79194599]),
 array([174.43321263]),
 array([167.19180399]),
 array([151.52748747]),
 array([190.88354941])]

In [ ]:
.